-- Online Quiz System Database Schema (PostgreSQL Compatible)

-- Drop existing tables
DROP TABLE IF EXISTS QUIZ_ASSIGNMENTS CASCADE;
DROP TABLE IF EXISTS ANSWERS CASCADE;
DROP TABLE IF EXISTS ATTEMPTS CASCADE;
DROP TABLE IF EXISTS QUESTIONS CASCADE;
DROP TABLE IF EXISTS QUIZZES CASCADE;
DROP TABLE IF EXISTS USERS CASCADE;

-- ==========================================================
-- 1. USERS
-- ==========================================================
CREATE TABLE USERS (
    USER_ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    ROLE VARCHAR(20) CHECK (ROLE IN ('TEACHER', 'STUDENT')) NOT NULL
);

-- ==========================================================
-- 2. QUIZZES
-- ==========================================================
CREATE TABLE QUIZZES (
    QUIZ_ID SERIAL PRIMARY KEY,
    TITLE VARCHAR(200) NOT NULL,
    DESCRIPTION VARCHAR(500),
    TIME_LIMIT INTEGER NOT NULL,
    CREATED_BY INTEGER REFERENCES USERS(USER_ID) ON DELETE SET NULL,
    ASSIGN_TO_ALL SMALLINT DEFAULT 1 CHECK (ASSIGN_TO_ALL IN (0, 1)),
    MAX_ATTEMPTS INTEGER DEFAULT 0 -- 0 means Unlimited
);

-- ==========================================================
-- 3. QUESTIONS
-- ==========================================================
CREATE TABLE QUESTIONS (
    QUESTION_ID SERIAL PRIMARY KEY,
    QUIZ_ID INTEGER REFERENCES QUIZZES(QUIZ_ID) ON DELETE CASCADE,
    QUESTION_TEXT VARCHAR(500) NOT NULL,
    OPTION1 VARCHAR(200) NOT NULL,
    OPTION2 VARCHAR(200) NOT NULL,
    OPTION3 VARCHAR(200) NOT NULL,
    OPTION4 VARCHAR(200) NOT NULL,
    CORRECT_OPTION INTEGER CHECK (CORRECT_OPTION BETWEEN 1 AND 4) NOT NULL,
    DIFFICULTY VARCHAR(20) CHECK (DIFFICULTY IN ('EASY', 'MEDIUM', 'HARD'))
);

-- ==========================================================
-- 4. ATTEMPTS
-- ==========================================================
CREATE TABLE ATTEMPTS (
    ATTEMPT_ID SERIAL PRIMARY KEY,
    STUDENT_ID INTEGER REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    QUIZ_ID INTEGER REFERENCES QUIZZES(QUIZ_ID) ON DELETE CASCADE,
    SCORE INTEGER NOT NULL,
    ATTEMPT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TIME_TAKEN INTEGER NOT NULL
);

-- ==========================================================
-- 5. ANSWERS
-- ==========================================================
CREATE TABLE ANSWERS (
    ANSWER_ID SERIAL PRIMARY KEY,
    ATTEMPT_ID INTEGER REFERENCES ATTEMPTS(ATTEMPT_ID) ON DELETE CASCADE,
    QUESTION_ID INTEGER REFERENCES QUESTIONS(QUESTION_ID) ON DELETE CASCADE,
    SELECTED_OPTION INTEGER NOT NULL,
    IS_CORRECT SMALLINT CHECK (IS_CORRECT IN (0, 1))
);

-- ==========================================================
-- 6. QUIZ_ASSIGNMENTS
-- ==========================================================
CREATE TABLE QUIZ_ASSIGNMENTS (
    QUIZ_ID INTEGER REFERENCES QUIZZES(QUIZ_ID) ON DELETE CASCADE,
    STUDENT_ID INTEGER REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    PRIMARY KEY (QUIZ_ID, STUDENT_ID)
);
